@startuml

Class CareTaker{
    - mementos: Memento
    + addMemento(Memento)
    + getMemento(): Memento
}

Class Memento {
    - article: String
    + Memento(String)
    + getArticle(): String
}

Class Originator {
    - article: String
    + set(String)
    + createMemento(Memento): String
}

CareTaker o--> Memento
Originator --> Memento


@enduml