@startuml
    Class House
    Class Kitchen
    Class Bathroom
    Class Bedroom
    Class Room

    Class Mortgage
    Class Mailbox

    House *-- "1" Kitchen
    House *-- "1" Bathroom
    House *-- "1.*" Bedroom
    House o-- "1 "Mailbox
    House --o "0..1" Mortgage

    Bedroom --|> Room
    Bathroom --|> Room
    Kitchen --|> Room

@enduml